"""
E2E Pytest Wrapper
==================
Wraps the programmatic scenario runner as pytest tests.
Run with: pytest tests/e2e/ -v

Datasets are auto-generated by conftest.py (session-scoped fixture).
"""
import json
from pathlib import Path

import pytest

BASE_DIR = Path(__file__).parent.parent.parent
SKILLS_DIR = BASE_DIR / "skills"
DATASETS_DIR = Path(__file__).parent / "datasets"


def _datasets_available():
    """Check if the datasets directory has files."""
    return DATASETS_DIR.exists() and any(DATASETS_DIR.iterdir())


# ── Import runner and verifier lazily ──────────────────────────────────

def _get_runner_and_verifier():
    """Import the scenario runner and verifier modules."""
    runner_path = Path(__file__).parent / "scenario_runner.py"
    verify_path = Path(__file__).parent / "verify_scenario.py"

    import importlib.util

    spec_r = importlib.util.spec_from_file_location("scenario_runner", runner_path)
    runner_mod = importlib.util.module_from_spec(spec_r)
    spec_r.loader.exec_module(runner_mod)

    spec_v = importlib.util.spec_from_file_location("verify_scenario", verify_path)
    verify_mod = importlib.util.module_from_spec(spec_v)
    spec_v.loader.exec_module(verify_mod)

    return runner_mod, verify_mod


# ── E2E Tests ──────────────────────────────────────────────────────────

class TestFullPipelineE2E:
    """Full pipeline: load -> profile -> clean -> validate -> stats -> chart -> report."""

    @pytest.mark.skipif(not _datasets_available(), reason="E2E datasets not generated")
    def test_full_pipeline_scenario(self, tmp_path):
        runner_mod, verify_mod = _get_runner_and_verifier()

        runner = runner_mod.ScenarioRunner(tmp_path, SKILLS_DIR)
        results = runner.run_full_pipeline(DATASETS_DIR / "full_pipeline_messy.csv")

        # All steps should succeed
        assert results["load"]["success"]
        assert results["profile"]["success"]
        assert results["clean"]["success"]
        assert results["stats"]["success"]
        assert results["chart"]["success"]
        assert results["report"]["success"]

        # Run verifier
        checks = verify_mod.verify_full_pipeline(str(tmp_path))
        failed = [c for c in checks if not c["pass"]]
        assert len(failed) == 0, f"Verification failures: {json.dumps(failed, indent=2)}"


class TestSelfHealingE2E:
    """Self-healing: encoding, mixed types, delimiter recovery."""

    @pytest.mark.skipif(not _datasets_available(), reason="E2E datasets not generated")
    def test_self_healing_scenario(self, tmp_path):
        runner_mod, verify_mod = _get_runner_and_verifier()

        runner = runner_mod.ScenarioRunner(tmp_path, SKILLS_DIR)
        results = runner.run_self_healing(DATASETS_DIR)

        # Encoding retry should succeed
        assert results["encoding"]["retry_success"], "Encoding retry failed"

        # Delimiter retry should succeed with correct column count
        assert results["delimiter"]["retry_success"], "Delimiter retry failed"
        assert results["delimiter"]["retry_cols"] >= 8, \
            f"Expected 8 columns, got {results['delimiter']['retry_cols']}"


class TestTextAnalysisE2E:
    """Text analysis: load JSONL -> profile -> patterns -> chart -> report."""

    @pytest.mark.skipif(not _datasets_available(), reason="E2E datasets not generated")
    def test_text_analysis_scenario(self, tmp_path):
        runner_mod, verify_mod = _get_runner_and_verifier()

        runner = runner_mod.ScenarioRunner(tmp_path, SKILLS_DIR)
        results = runner.run_text_analysis(DATASETS_DIR / "text_corpus.jsonl")

        # All steps should succeed
        assert results["load"]["success"]
        assert results["distributions"]["success"]
        assert results["patterns"]["success"]
        assert results["chart"]["success"]
        assert results["report"]["success"]

        # Run verifier
        checks = verify_mod.verify_text_analysis(str(tmp_path))
        failed = [c for c in checks if not c["pass"]]
        assert len(failed) == 0, f"Verification failures: {json.dumps(failed, indent=2)}"
